### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dataset' of undefined

### ISSUE THREAD

**Issue by zisheng-ai** [JakeDixon/zip-folder#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [zip-folder](https://github.com/JakeDixon/zip-folder) package 3.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'dataset' of undefined

```
At C:\Users\10037\.atom\packages\zip-folder\lib\zip-folder.coffee:64

TypeError: Cannot read property 'dataset' of undefined
    at Object.run (/packages/zip-folder/lib/zip-folder.coffee:64:33)
    at /packages/zip-folder/lib/zip-folder.coffee:23:86)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.21.0/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.21.0/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.21.0/resources/app/src/atom-environment.js:1354:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.21.0/resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:30.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:18.5.0 zip-folder:run (div.line.cursor-line.highlight-line.highlight-line-multi-line-solid-bottom)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
api-docs 0.0.6 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.5 
atom-html-preview 0.2.2 
atom-ide-ui 0.5.0 
atom-image-preview 0.0.0 
atom-material-ui 2.0.5 
atom-minify 0.8.0 
atom-ternjs 0.18.3 
autocomplete-en-cn 0.4.0 
autocomplete-modules 1.7.2 
autocomplete-paths 2.12.0 
autoprefixer 3.7.1 
color-picker 2.2.5 
copy-path 0.4.2 
css-snippets 1.1.0 
custom-title 1.0.1 
docblockr 0.11.0 
emmet 2.4.3 
expose 0.15.0 
file-icons 2.1.13 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.0.0 
hyperlink-hyperclick 1.3.4 
ide-html 0.3.0 
ide-php 0.6.9 
ide-typescript 0.6.1 
insert-timestamp 0.2.4 
intentions 1.1.5 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
language-ejs 0.4.0 
language-html-swig 2.0.1 
language-markdown 0.25.1 
less-autocompile 1.0.0 
linter-csslint 2.0.0 
linter-jshint 3.1.6 
linter-less 2.6.0 
linter-markdown 5.2.0 
linter-tidy 2.3.1 
markdown-preview-enhanced 0.14.11 
markdown-preview-plus 2.4.10 
markdown-scroll-sync 2.1.2 
markdown-table-editor 0.6.4 
markdown-themeable-pdf 1.2.0 
markdown-writer 2.7.2 
minimap 4.29.7 
minimap-codeglance 0.4.7 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.1 
one-dark-material-syntax 1.0.3 
open-file 1.4.0 
open-in-browsers 0.0.30 
pdf-view 0.59.0 
php-cs-fixer 4.1.1 
php-server 0.8.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
preview-inline 1.4.7 
regex-railroad-diagram 0.19.4 
Remote-FTP 1.2.5 
simple-drag-drop-text 0.3.6 
simplified-chinese-menu 5.3.4 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.3 
toggle-quotes 1.0.1 
tool-bar 1.1.0 
tool-bar-markdown-writer 0.3.0 
wordpress-api 1.2.2 
zip-folder 3.2.0 
```

**Comment by JakeDixon** [comment]
I am unable to replicate this, do you have any more information?

I have seen a similar error though, but only when the config section of the file is edited. Have you tried uninstalling and reinstalling the package?

**Comment by ajaykmankani** [comment]
i have also the same problem, i have installed it and when i pressed ctrl + shift + z the error occured.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 11 Pro
**Thrown From**: [zip-folder](https://github.com/JakeDixon/zip-folder) package 3.3.0


### Stack Trace

Uncaught TypeError: Cannot read property 'dataset' of undefined

```
At C:\Users\ajayk\.atom\packages\zip-folder\lib\zip-folder.coffee:76

TypeError: Cannot read property 'dataset' of undefined
    at Object.run (/packages/zip-folder/lib/zip-folder.coffee:76:34)
    at /packages/zip-folder/lib/zip-folder.coffee:30:86)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:352326)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1227728)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1223862)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:286651)
```

### Commands

```
     -8:58.4.0 core:backspace (input.hidden-input)
     -8:56.2.0 core:save (input.hidden-input)
     -7:39.4.0 core:backspace (input.hidden-input)
     -7:39.1.0 core:save (input.hidden-input)
     -7:04.1.0 editor:newline (input.hidden-input)
     -6:05.2.0 editor:toggle-line-comments (input.hidden-input)
     -6:04.0 core:undo (input.hidden-input)
     -6:00.6.0 key-binding-resolver:toggle (input.hidden-input)
     -5:58.2.0 settings-view:open (atom-pane.pane.active)
     -4:49.2.0 core:save (input.hidden-input)
     -4:42.8.0 tabs:close-saved-tabs (div.title)
     -4:40.4.0 key-binding-resolver:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:36.9.0 settings-view:open (atom-pane.pane.active)
     -4:27.5.0 core:backspace (input.hidden-input)
     -4:13.3.0 ftp-remote-edit:open-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:51.5.0 zip-folder:run (div.ftp-remote-edit-view.ftp-remote-edit-resizer.tool-panel)
```

### Non-Core Packages

```
atom-ftp-sass-compiler 0.2.0 
ftp-remote-edit 0.18.2 
minimap 4.40.0 
open-folder 1.5.0 
sass-compiler 0.4.0 
scss-compiler 1.0.0 
scss-onsave 0.3.0 
zip-folder 3.3.0 
```
